helloworld: helloworld.cpp log.cpp
	g++ -o helloworld helloworld.cpp log.cpp

clean:
	@if [ -f helloworld ]; then \
    	rm -f helloworld; \
	else \
    	echo "Target helloworld already cleaned"; \
	fi